import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google'
import "./globals.css";

import Providers from "./providers";
import { Drawer } from "@/components/Drawer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SpeedWeek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistMono.variable} antialiased flex bg-gray-100`}
      >
        <Providers>
          <div className="flex w-full min-h-screen">
            <div className="sticky top-0">
              <Drawer />
            </div>
            <div className="flex flex-col relative grow isolate text-gray-600">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}